<?php

namespace FormationBundle\Repository;

/**
 * BaneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaneRepository extends \Doctrine\ORM\EntityRepository
{
}
