<?php

namespace FormationBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL($mot)
    {
        return $this->createQueryBuilder('m')
            ->where('u.nom like :user')
            //->andWhere("m.createdAt < ?2")
            ->setParameter('user',$mot)
           // ->setParameter(2, $endDate)
            ->getQuery()
            ->getResult();
    }
}
