<?php

namespace HunterBundle\Repository;

use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{

}
