<?php

namespace HunterBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProduitsHorsStock(){
        return $this->getEntityManager()->createQuery(
            'SELECT p 
                                  FROM HunterBundle:Product p
                                  WHERE p.stock = 0')->getResult();
    }

    public function findProduitsEnReptureDeStock(){
        return $this->getEntityManager()->createQuery(
            'SELECT p 
                                  FROM HunterBundle:Product p
                                  WHERE p.stock > 0 AND p.stock<10')->getResult();
    }
}
